// import house images
import House1 from './assets/img/Mt-Center-Square/Soba1/s1-1.jpg';
import House2 from './assets/img/Mt-Center-Square/Soba2/s2-1.jpg';
import House3 from './assets/img/Mt-Center-Square/Soba3/s3-1.jpg';
import House4 from './assets/img/Mt-Center-Square/Soba4/s4-1.jpg';
import House5 from './assets/img/Mt-Center-Square/Soba5/s5-1.jpg';
import House6 from './assets/img/Mt-Center-Square/Cel-Stan/cs1.jpg';

// import house large images
import House1Lg1 from './assets/img/Mt-Center-Square/Soba1/s1-1.jpg';
import House1Lg2 from './assets/img/Mt-Center-Square/Soba1/s1-2.jpg';
import House1Lg3 from './assets/img/Mt-Center-Square/Soba1/s1-3.jpg';

import House2Lg from './assets/img/Mt-Center-Square/Soba2/s2-1.jpg';
import House3Lg from './assets/img/Mt-Center-Square/Soba3/s3-1.jpg';
import House4Lg from './assets/img/Mt-Center-Square/Soba4/s4-1.jpg';
import House5Lg from './assets/img/Mt-Center-Square/Soba5/s5-1.jpg';
import House6Lg from './assets/img/Mt-Center-Square/Cel-Stan/cs1.jpg';


// import agents images
import Agent1 from './assets/img/agents/agent1.png';
import Agent2 from './assets/img/agents/agent2.png';
import Agent3 from './assets/img/agents/agent3.png';
import Agent4 from './assets/img/agents/agent4.png';
import Agent5 from './assets/img/agents/agent5.png';
import Agent6 from './assets/img/agents/agent6.png';

export const housesData = [
  {
    id: 1,
    category : 'buy',
    type: 'House',
    name: 'Soba 1',
    description:
      'Discover city living at its finest. Stylish interiors, a gourmet kitchen, and panoramic city views await. Enjoy the convenience of downtown living with top-notch amenities. Your urban retreat is just steps away from trendy dining and cultural hotspots. Welcome home to luxury and location!',
    image: House1,
    images: [
      House1Lg1,
      House1Lg2,
      House1Lg3
    ],
    country: 'United States',
    address: 'Kej 13-ti Noemvri Skopje Kaj Dion',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '110000',
    agent: {
      image: Agent1,
      name: 'Marko/MT CS',
      phone: '0123 456 78910',
    },
  },
  {
    id: 2,
    category : 'rent',
    type: 'House',
    name: 'Soba 2',
    description:
      'Discover city living at its finest. Stylish interiors, a gourmet kitchen, and panoramic city views await. Enjoy the convenience of downtown living with top-notch amenities. Your urban retreat is just steps away from trendy dining and cultural hotspots. Welcome home to luxury and location!',
    image: House2,
    imageLg: House2Lg,
    country: 'Canada',
    address: 'Kej 13-ti Noemvri Skopje Kaj Dion',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '140000',
    agent: {
      image: Agent2,
      name: 'Daryl Hawker',
      phone: '0123 456 78910',
    },
  },
  {
    id: 3,
    category : 'buy',
    type: 'House',
    name: 'Soba 3',
    description:
      'Discover city living at its finest. Stylish interiors, a gourmet kitchen, and panoramic city views await. Enjoy the convenience of downtown living with top-notch amenities. Your urban retreat is just steps away from trendy dining and cultural hotspots. Welcome home to luxury and location!',
    image: House3,
    imageLg: House3Lg,
    country: 'United States',
    address: 'Kej 13-ti Noemvri Skopje Kaj Dion',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '170000',
    agent: {
      image: Agent3,
      name: 'Amado Smith',
      phone: '0123 456 78910',
    },
  },
  {
    id: 4,
    category : 'rent',
    type: 'House',
    name: 'Soba 4',
    description:
      'Discover city living at its finest. Stylish interiors, a gourmet kitchen, and panoramic city views await. Enjoy the convenience of downtown living with top-notch amenities. Your urban retreat is just steps away from trendy dining and cultural hotspots. Welcome home to luxury and location!',
    image: House4,
    imageLg: House4Lg,
    country: 'Canada',
    address: 'Kej 13-ti Noemvri Skopje Kaj ????',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2016',
    price: '200000',
    agent: {
      image: Agent4,
      name: 'Kaitlyn Gonzalez',
      phone: '0123 456 78910',
    },
  },
  {
    id: 5,
    category : 'buy',
    type: 'House',
    name: 'Soba 5',
    description:
      'Discover city living at its finest. Stylish interiors, a gourmet kitchen, and panoramic city views await. Enjoy the convenience of downtown living with top-notch amenities. Your urban retreat is just steps away from trendy dining and cultural hotspots. Welcome home to luxury and location!',
    image: House5,
    imageLg: House5Lg,
    country: 'United States',
    address: 'Kej 13-ti Noemvri Skopje Kaj Dion',
    bedrooms: '5',
    bathrooms: '3',
    surface: '4200 sq ft',
    year: '2015',
    price: '210000',
    agent: {
      image: Agent5,
      name: 'Grover Robinson',
      phone: '0123 456 78910',
    },
  },
  {
    id: 6,
    category : 'rent',
    type: 'House',
    name: 'Soba 6',
    description:
      'Discover city living at its finest. Stylish interiors, a gourmet kitchen, and panoramic city views await. Enjoy the convenience of downtown living with top-notch amenities. Your urban retreat is just steps away from trendy dining and cultural hotspots. Welcome home to luxury and location!',
    image: House6,
    imageLg: House6Lg,
    country: 'Canada',
    address: 'Vladimir Komarov A6? Skopje',
    bedrooms: '6',
    bathrooms: '3',
    surface: '6200 sq ft',
    year: '2014',
    price: '220000',
    agent: {
      image: Agent6,
      name: 'Karen Sorensen',
      phone: '0123 456 78910',
    },
  },
  // {
  //   id: 7,
  //   category : 'sell',
  //   type: 'Apartment',
  //   name: 'Apartment 1',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment1,
  //   imageLg: Apartment1Lg,
  //   country: 'Canada',
  //   address: '32 Pawnee Street Butte, MT 59701',
  //   bedrooms: '2',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2012',
  //   price: '20000',
  //   agent: {
  //     image: Agent7,
  //     name: 'Jawhar Shamil Naser',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 8,
  //   category : 'rent',
  //   type: 'Apartment',
  //   name: 'Apartment 2',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment2,
  //   imageLg: Apartment2Lg,
  //   country: 'United States',
  //   address: '28 Westport Dr. Warminster, PA 18974',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1000 sq ft',
  //   year: '2011',
  //   price: '30000',
  //   agent: {
  //     image: Agent8,
  //     name: 'Juana Douglass',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 9,
  //   type: 'Apartment',
  //   category : 'sell',
  //   name: 'Apartament 3',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment3,
  //   imageLg: Apartment3Lg,
  //   country: 'United States',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '2',
  //   bathrooms: '1',
  //   surface: '1100 sq ft',
  //   year: '2011',
  //   price: '40000',
  //   agent: {
  //     image: Agent9,
  //     name: 'Jerry Schenck',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 10,
  //   type: 'House',
  //   category : 'rent',
  //   name: 'House 7',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: House7,
  //   imageLg: House7Lg,
  //   country: 'Canada',
  //   address: '7240C Argyle St. Lawndale, CA 90260',
  //   bedrooms: '5',
  //   bathrooms: '3',
  //   surface: '3200 sq ft',
  //   year: '2015',
  //   price: '117000',
  //   agent: {
  //     image: Agent10,
  //     name: 'Vera Levesque',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 11,
  //   type: 'House',
  //   category : 'sell',
  //   name: 'House 8',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: House8,
  //   imageLg: House8Lg,
  //   country: 'Canada',
  //   address: '798 Talbot St. Bridgewater, NJ 08807',
  //   bedrooms: '7',
  //   bathrooms: '2',
  //   surface: '2200 sq ft',
  //   year: '2019',
  //   price: '145000',
  //   agent: {
  //     image: Agent11,
  //     name: 'Sofia Gomes',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 12,
  //   type: 'House',
  //   category : 'rent',
  //   name: 'House 9',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: House9,
  //   imageLg: House9Lg,
  //   country: 'United States',
  //   address: '2 Glen Creek St. Alexandria, VA 22304',
  //   bedrooms: '4',
  //   bathrooms: '4',
  //   surface: '4600 sq ft',
  //   year: '2015',
  //   price: '139000',
  //   agent: {
  //     image: Agent12,
  //     name: 'Raymond Hood',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 13,
  //   type: 'House',
  //   category : 'sell',
  //   name: 'House 10',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: House10,
  //   imageLg: House10Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '5',
  //   bathrooms: '2',
  //   surface: '5200 sq ft',
  //   year: '2014',
  //   price: '180000',
  //   agent: {
  //     image: Agent1,
  //     name: 'Patricia Tullert',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 14,
  //   type: 'House',
  //   category : 'rent',
  //   name: 'House 11',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: House11,
  //   imageLg: House11Lg,
  //   country: 'United States',
  //   address: '28 Westport Dr. Warminster, PA 18974',
  //   bedrooms: '5',
  //   bathrooms: '2',
  //   surface: '3200 sq ft',
  //   year: '2011',
  //   price: '213000',
  //   agent: {
  //     image: Agent2,
  //     name: 'Daryl Hawker',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 15,
  //   type: 'House',
  //   category : 'buy',
  //   name: 'House 12',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: House12,
  //   imageLg: House12Lg,
  //   country: 'Canada',
  //   address: '32 Pawnee Street Butte, MT 59701',
  //   bedrooms: '4',
  //   bathrooms: '3',
  //   surface: '5200 sq ft',
  //   year: '2013',
  //   price: '221000',
  //   agent: {
  //     image: Agent3,
  //     name: 'Amado Smith',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 16,
  //   type: 'Apartment',
  //   category : 'rent',
  //   name: 'Apartment 16',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment4,
  //   imageLg: Apartment4Lg,
  //   country: 'Canada',
  //   address: '32 Pawnee Street Butte, MT 59701',
  //   bedrooms: '2',
  //   bathrooms: '1',
  //   surface: '1300 sq ft',
  //   year: '2011',
  //   price: '21000',
  //   agent: {
  //     image: Agent4,
  //     name: 'Kaitlyn Gonzalez',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 17,
  //   type: 'Apartment',
  //   category : 'buy',
  //   name: 'Apartment 17',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment5,
  //   imageLg: Apartment5Lg,
  //   country: 'United States',
  //   address: '28 Westport Dr. Warminster, PA 18974',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1000 sq ft',
  //   year: '2012',
  //   price: '32000',
  //   agent: {
  //     image: Agent5,
  //     name: 'Grover Robinson',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 18,
  //   type: 'Apartment',
  //   category : 'buy',
  //   name: 'Apartment 19',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 19,
  //   type: 'Apartment',
  //   category : 'sell',
  //   name: 'Apartment 19',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 20,
  //   type: 'Apartment',
  //   category : 'buy',
  //   name: 'Apartment 20',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 21,
  //   type: 'Apartment',
  //   category : 'sell',
  //   name: 'Apartment 21',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 22,
  //   type: 'Apartment',
  //   category : 'rent',
  //   name: 'Apartment 22',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 23,
  //   category : 'buy',
  //   type: 'Apartment',
  //   name: 'Apartment 23',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 24,
  //   category : 'rent',
  //   type: 'Apartment',
  //   name: 'Apartment 24',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 25,
  //   category : 'sell',
  //   type: 'Apartment',
  //   name: 'Apartment 25',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 26,
  //   category : 'rent',
  //   type: 'Apartment',
  //   name: 'Apartment 26',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '110000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
  // {
  //   id: 27,
  //   category : 'rent',
  //   type: 'Apartment',
  //   name: 'Apartment 28',
  //   description:
  //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
  //   image: Apartment6,
  //   imageLg: Apartment6Lg,
  //   country: 'Canada',
  //   address: '84 Woodland St. Cocoa, FL 32927',
  //   bedrooms: '3',
  //   bathrooms: '1',
  //   surface: '1200 sq ft',
  //   year: '2010',
  //   price: '38000',
  //   agent: {
  //     image: Agent6,
  //     name: 'Karen Sorensen',
  //     phone: '0123 456 78910',
  //   },
  // },
];
